MyBlog/Areas/Admin/Controllers/PostItemsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Domain;
using MyBlog.Domain.Entities;
using MyBlog.Service;

namespace MyBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Route("fileupload")]
    public class PostItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment; //для сохранения картинок

        public PostItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            ViewBag.isAut = HttpContext.User.Identity.IsAuthenticated;
            ViewBag.Name = HttpContext.User.Identity.Name;
            var entity = id == default ? new PostItem() : dataManager.PostItems.GetPostItemById(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(PostItem model, IFormFile titleImageFile/*титульная картинка*/)
        {
            ViewBag.isAut = HttpContext.User.Identity.IsAuthenticated;
            ViewBag.Name = HttpContext.User.Identity.Name;
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "img/", titleImageFile.FileName), FileMode.Create);
                    titleImageFile.CopyTo(stream);
                }
                dataManager.PostItems.SavePostItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            ViewBag.isAut = HttpContext.User.Identity.IsAuthenticated;
            ViewBag.Name = HttpContext.User.Identity.Name;
            dataManager.PostItems.DeletePostItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

MyBlog/Areas/Admin/Views/PostItems/Edit.cshtml
@model PostItem
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>
<script>
    window.onload = function () {
        CKEDITOR.replace('@Html.IdFor(x=>x.Text)', {
            height: 400,
            filebrowserUploadUrl: '/fileupload/upload_ckeditor'/*,
            filebrowserBrowseUrl: '/fileupload/filebrowse'*/
        });
        //editor.updateElement();
    };
</script>
<div class="container py-5">
    <div>
        <h2>@strTitle</h2>
        <div>
            <form asp-area="Admin" asp-controller="PostItems" asp-action="Edit" method="post" enctype="multipart/form-data">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="DateAdded" />
                <input type="hidden" asp-for="TitleImagePath" />

                <div asp-validation-summary="All"></div>
                <div class="div-box">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" />
                    <span asp-validation-for="Title"></span>
                </div>
                <div class="div-box">
                    <label asp-for="Subtitle"></label>
                    <input asp-for="Subtitle" />
                    <span asp-validation-for="Subtitle"></span>
                </div>
                <div class="div-box">
                    <label asp-for="Text"></label>
                    <textarea asp-for="Text"></textarea>
                    <span asp-validation-for="Text"></span>
                </div>
                <div class="div-box">
                    <label asp-for="TitleImagePath"></label>
                    <input type="file" name="titleImageFile" id="titleImageFile" />
                    <div>
                        <img class="img-block" src="~/img/@Model.TitleImagePath" />
                    </div>
                </div>
                <input type="submit" value="Сохранить" />
            </form>
        </div>
    </div>
</div>