MyBlog/Areas/Admin/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using MyBlog.Domain;
using MyBlog.Domain.Entities;
using MyBlog.Service;

namespace MyBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        private readonly DataManager dataManager;
        public TextFieldsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Edit(string codeWord)
        {
            ViewBag.isAut = HttpContext.User.Identity.IsAuthenticated;
            ViewBag.Name = HttpContext.User.Identity.Name;
            var entity = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(TextField model)
        {
            ViewBag.isAut = HttpContext.User.Identity.IsAuthenticated;
            ViewBag.Name = HttpContext.User.Identity.Name;
            if (ModelState.IsValid)
            {
                dataManager.TextFields.SaveTextField(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

MyBlog/Areas/Admin/Views/TextFields/Edit.cshtml
@model TextField
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div class="container py-5">
    <div>
        <h2>@strTitle</h2>
        <div>
            <form asp-area="Admin" asp-controller="TextFields" asp-action="Edit" method="post" enctype="multipart/form-data">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="DateAdded" />
                <input type="hidden" asp-for="CodeWord" />

                <div asp-validation-summary="All"></div>
                <div class="div-box">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" />
                    <span asp-validation-for="Title"></span>
                </div>
                <div class="div-box">
                    <label asp-for="Text"></label>
                    <textarea asp-for="Text"></textarea>
                    <span asp-validation-for="Text"></span>
                </div>
                <input type="submit" value="Сохранить" />
            </form>
        </div>
    </div>
</div>


    <script>
    window.onload = function() {
        CKEDITOR.replace('@Html.IdFor(x=>x.Text)', {
            removePlugins: 'image'
        });
    }
    </script>